version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: alquileres_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: alquileres_db
      MYSQL_USER: alquiler_user
      MYSQL_PASSWORD: pass1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  backend:
    build: .
    container_name: alquileres_api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      RUN_ENV: docker            
      DB_USER: alquiler_user     
      DB_PASSWORD: pass1234       
      DB_HOST: db                 
      DB_PORT: 3306
      DB_NAME: alquileres_db
      JWT_SECRET_KEY: super_key_123
      JWT_EXPIRES_IN: 900
      FLASK_ENV: development
      MAIL_SERVER: smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USE_TLS: "true"
      MAIL_USE_SSL: "false"
      MAIL_USERNAME: "tu-user"
      MAIL_PASSWORD: "tu-pass"
      MAIL_DEFAULT_SENDER: "auto_track_alquileres@gmail.com"
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  db_data:
